/**
 * Detailed failure reasons for each step - helps user understand why a step failed
 */
export enum FailureReason {
  // Validation failures
  INVALID_CUSTOMER_ID = 'INVALID_CUSTOMER_ID',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_LOAN_TYPE = 'INVALID_LOAN_TYPE',
  INVALID_CREDIT_SCORE = 'INVALID_CREDIT_SCORE',
  INVALID_MONTHLY_INCOME = 'INVALID_MONTHLY_INCOME',

  // Fraud check failures
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
  FRAUDULENT_CUSTOMER = 'FRAUDULENT_CUSTOMER',
  BLACKLISTED_USER = 'BLACKLISTED_USER',

  // Guarantor check failures
  GUARANTOR_REQUIRED = 'GUARANTOR_REQUIRED',

  // Credit check failures
  LOW_CREDIT_SCORE = 'LOW_CREDIT_SCORE',
  CREDIT_SCORE_MANUAL_REVIEW = 'CREDIT_SCORE_MANUAL_REVIEW',

  // Manager/Final approval failures
  INCOME_RATIO_TOO_HIGH = 'INCOME_RATIO_TOO_HIGH',
  FINAL_APPROVAL_REJECTED = 'FINAL_APPROVAL_REJECTED',

  // System failures
  REQUEST_EXPIRED = 'REQUEST_EXPIRED',
}
